import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getNavbar } from '../dataHelpers'
import Navbar from '../components/Navbar'
import { NodeHtmlMarkdown, NodeHtmlMarkdownOptions } from 'node-html-markdown'

export default function Home({data, navBar}) {

  const text ={__html: data}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navBar = {navBar} />

      <main className={styles.main}>
        <h1 className={styles.title}>
         Simon&apos;s Blog
          <br></br> 
          <a style={{ fontSize: '24px' }} href="https://nextjs.org">Go To Wordpress Version ?</a>
        </h1>

  

        <div className={styles.grid}>
          <section>
            {data.map((item, i) => {
              const text={__html:item.title.rendered}
              return(
                <div key={i} className={styles.card}>
                <Link href={`/posts/${item.id}`}>
                  <li style={{ listStyleType: 'none' }}>
                    <a dangerouslySetInnerHTML={text}></a>
                  </li>
                </Link>
            </div>
              )
            })}
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context){
  const dataDump = await axios.get('http://www.simoncolman.com/wp-json/wp/v2/posts')
  const {data} = dataDump
  const nav = await getNavbar()
  return {
    props:{
      data: data,
      navBar: nav
    }
  }
}
